version: '3'
services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - /dev/null:/var/www/html/index.php
      - ./docker-data/public-files:/var/www/html/files
      - ./docker-data/assets:/var/www/html/assets
  ##### versão sem ssl
      - ./compose/production/nginx.conf:/etc/nginx/conf.d/default.conf

  ##### versão com ssl
    #  - ./compose/production/nginx-ssl.conf:/etc/nginx/conf.d/default.conf
    #  - ./docker-data/certs/conf:/etc/letsencrypt
    #  - ./docker-data/certs/www:/var/www/certbot
    ports:
     - "80:80"
     - "443:443"
    depends_on:
      - mapas
    links:
      - mapas
  
  mapas:
    env_file:
      - .env
    image: secultceara/mapa:5.7.1
    restart: unless-stopped
    volumes:
      - ./docker-data/assets:/var/www/html/assets
      #- ./docker-data/public-files:/var/www/html/files
      #- ./docker-data/private-files:/var/www/private-files
      #- ./docker-data/saas-files:/var/www/SaaS
    links:
      - db
      - redis
      - sessions
    depends_on:
      - db
      - redis
      - sessions

  redis:
    image: redis:6
    command: --maxmemory 256Mb --maxmemory-policy allkeys-lru
    restart: unless-stopped
 
  sessions:
    image: redis:6
    command: --maxmemory 384Mb --maxmemory-policy allkeys-lru
    restart: unless-stopped
    volumes:
      - ./docker-data/sessions:/data

  db:
    image: postgis/postgis:14-master
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=mapas
      - POSTGRES_USER=mapas
      - POSTGRES_DB=mapas
    volumes:
      #- ./compose/db/dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - ./docker-data/db-data:/var/lib/postgresql/data
    

## Em ambiente de homologação pode ser uma boa ideia utilizar o mailhog para testar 
## o envio de emails e também prevenir que emails de tete sejam disparados acidentalmente 
## para os usuários no caso de o ambiente de homologação utilizar um banco de dados cópia
## de produção

  # mailhog: 
  #   image: mailhog/mailhog
  #   ports:
  #     - "8025:8025"
